const { chromium } = require('C:/Users/Natsuki/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert = require('node:assert/strict');

(async () => {
  const browser = await chromium.launch({channel:'msedge', headless:true});
  const a = await browser.newContext({viewport:{width:390,height:844}});
  const b = await browser.newContext({viewport:{width:1280,height:900}});
  const pageA = await a.newPage();
  const pageB = await b.newPage();
  const errors = [];
  for (const page of [pageA,pageB]) page.on('pageerror', error => errors.push(error.message));
  try {
    await pageA.goto('http://127.0.0.1:8766');
    await pageA.locator('.memory-panel summary').nth(1).click();
    await pageA.locator('#memory-content').fill('検証用の記憶');
    await pageA.locator('#memory-form button').click();
    await pageA.getByText('記憶を保存しました。', {exact:true}).waitFor();
    await pageA.locator('.account-panel summary').click();
    await pageA.locator('#account-username').fill('browser_test');
    await pageA.locator('#account-password').fill('browser-test-password-123');
    await pageA.locator('#account-migrate-confirm').check();
    await pageA.locator('#account-register').click();
    await pageA.locator('#account-new-recovery-code').waitFor();
    let recoveryCode = await pageA.locator('#account-new-recovery-code').textContent();
    assert.equal(recoveryCode.length, 43);
    await pageA.locator('#account-recovery-continue').click();
    await pageA.waitForFunction(() => document.querySelector('#account-label').textContent.includes('browser_test'));
    await pageA.locator('.account-panel summary').click();
    await pageA.locator('#account-reissue-password').fill('browser-test-password-123');
    await pageA.locator('#account-reissue').click();
    await pageA.locator('#account-new-recovery-code').waitFor();
    const replacement = await pageA.locator('#account-new-recovery-code').textContent();
    assert.notEqual(replacement, recoveryCode);
    recoveryCode = replacement;
    await pageA.locator('#account-recovery-continue').click();
    await pageA.waitForFunction(() => document.querySelector('#account-label').textContent.includes('browser_test'));
    assert.equal(await pageA.locator('#memory-list textarea').first().inputValue(), '検証用の記憶');
    await pageB.goto('http://127.0.0.1:8766');
    await pageB.locator('.account-panel summary').click();
    await pageB.locator('#account-username').fill('browser_test');
    await pageB.locator('#account-password').fill('browser-test-password-123');
    await pageB.locator('#account-login').click();
    await pageB.waitForFunction(() => document.querySelector('#account-label').textContent.includes('browser_test'));
    assert.equal(await pageB.locator('#memory-list textarea').first().inputValue(), '検証用の記憶');
    await pageA.locator('.account-panel summary').click();
    await pageA.locator('#account-logout').click();
    await pageA.waitForFunction(() => document.querySelector('#account-label').textContent.includes('未ログイン'));
    assert.equal(await pageA.locator('#memory-list textarea').count(), 0);
    assert.equal(await pageB.locator('#memory-list textarea').first().inputValue(), '検証用の記憶');
    await pageA.locator('.account-panel summary').click();
    await pageA.locator('#account-username').fill('browser_test');
    await pageA.locator('#account-password').fill('new-browser-password-123');
    await pageA.locator('#account-recovery-toggle').click();
    await pageA.locator('#account-recovery-code').fill(recoveryCode);
    await pageA.locator('#account-recover').click();
    await pageA.locator('#account-new-recovery-code').waitFor();
    await pageA.locator('#account-recovery-continue').click();
    await pageA.waitForFunction(() => document.querySelector('#account-label').textContent.includes('browser_test'));
    assert.equal(await pageA.locator('#memory-list textarea').first().inputValue(), '検証用の記憶');
    await pageB.reload();
    await pageB.waitForFunction(() => document.querySelector('#account-label').textContent.includes('未ログイン'));
    assert.equal(await pageB.locator('#memory-list textarea').count(), 0);
    assert.equal(await pageA.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    assert.deepEqual(errors, []);
    console.log('PASS: account register/migrate, cross-browser login, logout, recovery, session revocation, mobile width, no JS errors');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
